### ISSUE TITLE
Java 11 is not default

### ISSUE THREAD

**Issue by sanitas2** [ansiblebit/oracle-java#109]
Readme suggests that running:

```
- hosts: servers
  roles:
      - role: ansiblebit.oracle-java
```

Would install JDK11. When I run it, logs tell me:

> fatal: [host1]: FAILED! => {"changed": false, "dest": "/usr/local/src/jdk-8u112-linux-x64.rpm", "msg": "Request failed", "response": "HTTP Error 404: Not Found"

which suggests it downloads JDK8.

**Comment by steenzout** [comment]
are you sure you are using the latest version of this role?

https://github.com/ansiblebit/oracle-java/blob/master/defaults/redhat.yml

**Comment by steenzout** [comment]
ping me here if you still have a problem.
