### ISSUE TITLE
there's a 404 error when downloading the java PRM from oracle

### ISSUE THREAD

**Issue by eMe-404** [ansiblebit/oracle-java#113]
here what my playbook .yml file looks like
```
- hosts: localhost
  connection: local
  gather_facts: yes
  become: true
  roles:
    - { role: ansiblebit.oracle-java,
        oracle_java_use_defaults: no,
        oracle_java_dir_source: '/usr/local/src',
        oracle_java_download_timeout: 60  ,
        oracle_java_rpm_filename: 'jdk-8u191-linux-x64.rpm',
        oracle_java_home: '/usr/java/default',
        oracle_java_os_supported: yes,
        oracle_java_rpm_url: 'https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.rpm',
        oracle_java_rpm_validate_certs: yes,
        oracle_java_set_as_default: no,
        oracle_java_version_string: 1.8.0_191
    }
```

and I get the following result when the task runs, I tried different versions of **java PRM** but the result is same
![image](https://user-images.githubusercontent.com/31622637/56494780-06dfbe80-6526-11e9-86b3-47e1e46a2c72.png)

**Comment by eMe-404** [comment]
the **url** is correct because I can directly download the same JAVA PRM from my local terminal by `wget`

**Comment by mauriziod** [comment]
oracle-java 8 support has been officially removed from www.webupd8.org and most linux repos.

**Comment by steenzout** [comment]
this is what I get from `wget`:

```$ ls -lha jdk-8u201-linux-x64.rpm 
-rw-r--r-- 1 steenzout steenzout 5.2K Mar 20  2012 jdk-8u201-linux-x64.rpm
```

this is definitely not _it_.

as @mauriziod explained, JDK 8 is not supported any longer.
