### ISSUE TITLE
Add Ansible galaxy link

### ISSUE THREAD

**Issue by kosssi** [ansiblebit/oracle-java#2]
You can edit your repository for add ansible galaxy link : https://galaxy.ansible.com/list#/roles/3375
like here : https://github.com/kosssi/ansible-role-composer

Your model is beautiful ;)

**Comment by steenzout** [comment]
@kosssi I've just added on this repo.
thank you for pointing that out and for the praise.

check https://github.com/ansiblebit/primogen.
it has the base setup for all the roles I do.
if you see anything else I can do to improve let me know.
