### ISSUE TITLE
Disable debug by default

### ISSUE THREAD

**Issue by sveneh** [ansiblebit/oracle-java#24]
Thanks for writing this excellent role.

I'd recommend to have debug output disabled by default. Seems to be more logical. By default I just want to use the role and I don't care about the output. Only when I have problems, I'd like to enable debug output. Now I have to use `--skip-tag=debug` to all my commands to not get spammed with unnecessary output.

**Comment by steenzout** [comment]
@sveneh give me 15 minutes...

**Comment by sveneh** [comment]
wow, you are fast!

**Comment by steenzout** [comment]
I wanted to clean this role up for quite some time.
just waiting to have tests to pass...

**Comment by steenzout** [comment]
@sveneh check [v4.14.0](https://github.com/ansiblebit/oracle-java/releases/tag/v4.14.0).

cheers!

_please star the repo, thank you!_
