### ISSUE TITLE
change sudo to become

### ISSUE THREAD

**Issue by rompic** [ansiblebit/oracle-java#29]
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default).
This 
feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.

**Comment by steenzout** [comment]
@rompic I'll handle this asap.

**Comment by steenzout** [comment]
testing patch...

**Comment by steenzout** [comment]
please use [launchpad-ppa-webupd8 4.14.0](https://github.com/ansiblebit/launchpad-ppa-webupd8/releases/tag/4.14.0) and [ansiblebit.oracle-java 4.14.4](https://github.com/ansiblebit/oracle-java/releases/tag/4.14.4).

cheers!

**Comment by steenzout** [comment]
problem should have been solved.
let me know if you still see this warning.

**Comment by rompic** [comment]
nice!

**Comment by steenzout** [comment]
if you like the roles please star the repo(s). ;)

thank you for reporting this issue!
