### ISSUE TITLE
I see that this is not tested against centos 6

### ISSUE THREAD

**Issue by xcalibre0** [ansiblebit/oracle-java#31]
Does this mean you simply dont run that test?  Or, do you know for a fact that it wont work on centos 6?

I'm running into errors with the ansible yum package from python 2.6 not being able to read the rpm header.

"module_stderr": "", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_sU5b4e/ansible_module_yum.py\", line 1084, in <module>\r\n    main()\r\n  File \"/tmp/ansible_sU5b4e/ansible_module_yum.py\", line 1073, in main\r\n    disablerepo, disable_gpg_check, exclude, repoquery)\r\n  File \"/tmp/ansible_sU5b4e/ansible_module_yum.py\", line 989, in ensure\r\n    res = install(module, pkgs, repoq, yum_basecmd, conf_file, en_repos, dis_repos)\r\n  File \"/tmp/ansible_sU5b4e/ansible_module_yum.py\", line 591, in install\r\n    nvra = local_nvra(module, spec)\r\n  File \"/tmp/ansible_sU5b4e/ansible_module_yum.py\", line 506, in local_nvra\r\n    header = ts.hdrFromFdno(fd)\r\n  File \"/usr/lib64/python2.6/site-packages/rpm/transaction.py\", line 154, in hdrFromFdno\r\n    raise rpm.error(\"error reading package header\")\r\n_rpm.error: error reading package header\r\n",

**Comment by steenzout** [comment]
@xcalibre0 I don't test against CentOS 6.

I definitely don't test against servers/virtual machines that have a Python 2.6 interpreter.

[here](https://github.com/ansiblebit/oracle-java/blob/master/tests/boxes.yml) are the versions of the Vagrant boxes I test against (using default Python interpreter that comes with those distributions/releases).

**Comment by steenzout** [comment]
_no answer back_.
