### ISSUE TITLE
RPM not downloaded

### ISSUE THREAD

**Issue by hryamzik** [ansiblebit/oracle-java#34]
```
TASK [oracle-java : download Java RPM] *****************************************
fatal: [vagrant]: FAILED! => {"changed": false, "dest": "/usr/local/src/jdk-8u121-linux-x64.rpm", "failed": true, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "http://download.oracle.com/otn-pub/java/jdk/8u121-b13/jdk-8u121-linux-x64.rpm"}
```

Not sure how to address this, looks like correct URL is `http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-linux-x64.rpm`

**Comment by steenzout** [comment]
@hryamzik I've managed to replicate the issue as well.

I'll post a fix within the hour.

**Comment by steenzout** [comment]
I hard-code the URL on the task YAML file and it's definitely not it.

it may be [this](https://github.com/ansible/ansible/issues/10902)

**Comment by steenzout** [comment]
I cannot set use `121` update.
it will fail the download.

the [ansible issue](https://github.com/ansible/ansible/issues/10902) _seems_ to be related.

**Comment by steenzout** [comment]
I'll try later tonight to rollback the use of `get_url` and see if that will make it work again.

**Comment by hryamzik** [comment]
Well, I've updated URL and it worked for me:
```yml
oracle_java_rpm_url: "http://download.oracle.com/otn-pub/java/jdk/{{ oracle_java_version }}u{{ oracle_java_version_update }}-b{{ oracle_java_version_build }}/e9e7ea248e2c4826b92b3f075a80e441/{{ oracle_java_rpm_filename }}"
```

**Comment by steenzout** [comment]
will it work for older versions? or I'll need to do a `when X` for update < 121 and another for update >= 121?

**Comment by steenzout** [comment]
I got my answer... I'll need the `when` statement:

```
$ tox -e py27-ansible22 -- --box centos7-64.vagrant.dev
(...)
TASK [oracle-java : download Java RPM] *****************************************
fatal: [centos7-64.vagrant.dev]: FAILED! => {"changed": false, "dest": "/usr/local/src/jdk-8u112-linux-x64.rpm", "failed": true, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "http://download.oracle.com/otn-pub/java/jdk/8u112-b15/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u112-linux-x64.rpm"}
	to retry, use: --limit @/Users/steenzout/Projects/github/ansiblebit/oracle-java/tests/test.retry

PLAY RECAP *********************************************************************
centos7-64.vagrant.dev     : ok=6    changed=1    unreachable=0    failed=1   

__________________________________________________________________________ summary ___________________________________________________________________________
  py27-ansible22: commands succeeded
  congratulations :)
```

**Comment by steenzout** [comment]
I've added info on the README file to help people stuck with this issue.

another possibility is to make the URL expression more complex (ternary if?).

**Comment by hryamzik** [comment]
Oracle might have changed URLs, I didn't check other versions yet. Parsing of HTML could be an option, but they may change it's URL as well...

**Comment by avishefi** [comment]
I'm getting 404 for JDK 8 update 112 and 131, looks like Oracle changed their download URLs for more than just version 121 as stated in the README.

**Comment by steenzout** [comment]
@avishefi at the time that's what I saw.
if you see something different I suggest you override the variable by hand.
I'll test it later.

**Comment by hryamzik** [comment]
Here's how to get the latest rpm url:

```yml
    - name: get latest JDK download page
      uri:
        url: http://www.oracle.com/technetwork/java/javase/downloads/index.html
        return_content: yes
      register: result
    
    - name: get lastest JDK rpm url
      uri: url="{{ result.content.replace('\n','')|regex_replace('.*(/technetwork/java/javase/downloads/jdk8-downloads.*?.html).*', 'http://www.oracle.com/\1') }}"
           return_content=yes
      register: result

    - debug: msg="{{ result.content.replace('\n','')|regex_replace('.*(https?://download.oracle.com/.*?/jdk-.*?-linux-x64.rpm).*', '\1') }}" 
```

BTW, `x64` shouldn't be hardcoded, it can be taken from facts.

@steenzout any ideas how to properly integrate this? I can see two options:

1. Fallback to latest when download fails
2. `latest` option with no version check
3. `latest` option with getting numbers from these pages

**Comment by steenzout** [comment]
@hryamzik maybe the code snippet you sent would be better in the example playbook as a set of pre-tasks that scraps Oracle download page to discover the version and URL to be used to download the latest version (for RedHat-based distributions).

for those who really want a specific version you would still have the same problem though.
you need to know the download URL for that version.
I did some research yesterday and I saw a case where someone was basically keeping track of download URLs per version.

what do you think?

**Comment by hryamzik** [comment]
I think that role with no arguments should work and install latest stable version. That said I'd add support for version `latest` and set defaults to it. But I didn't check how difficult is it to implement for other OSes. That also means version has to be grabbed from URL to compare with installed one.

**Comment by steenzout** [comment]
this would be a Redhat-based only change.
for Debian-based distributions I'm picking up the latest debian package from webupd8 so the version parameter is irrelevant.

I think I have a path for resolution then.
I'll try and handle this on the weekend (no time this week).

**Comment by hryamzik** [comment]
I might be able to send a PR tomorrow.

**Comment by devtakh** [comment]
Hi,
I am also facing the same issue. Is there a fix/workaround that I can pull from?

**Comment by steenzout** [comment]
@devtakh you can try and use this https://github.com/ansiblebit/oracle-java/commit/facacbd56e918093fab3ba60e8d814a503aab4dd commit.

**Comment by steenzout** [comment]
@devtakh you can also set `oracle_java_rpm_url` yourself.

on the README.md:
```
WARNING: in RedHat based distributions, if you want to use oracle_java_version_update: 121, you'll have to set oracle_java_rpm_url: "http://download.oracle.com/otn-pub/java/jdk/{{ oracle_java_version }}u{{ oracle_java_version_update }}-b{{ oracle_java_version_build }}/e9e7ea248e2c4826b92b3f075a80e441/{{ oracle_java_rpm_filename }}".
```

**Comment by devtakh** [comment]
Great. Thanks much @steenzout .

**Comment by hryamzik** [comment]
BTW, what prevents #43 from being merged to master?

**Comment by steenzout** [comment]
I still haven't had time to workout the issues with Java 7.

**Comment by hryamzik** [comment]
I'm not sure if it works with current master (really shouldn't), I'll try to check this on Friday.

**Comment by hryamzik** [comment]
OK, current master doesn't work for me at all:

```
fatal: [centos7]: FAILED! => {"changed": false, "dest": "/usr/local/src/jdk-7u80-linux-x64.rpm", "failed": true, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.rpm"}
```

Tried with

```yml
    - role: oracle-java
      oracle_java_version: 7
      oracle_java_version_update: 80
```

May be related to #47.

**Comment by hryamzik** [comment]
@steenzout if java 7 is broken in master too I think we a fine to merge this. ;-)

**Comment by steenzout** [comment]
@hryamzik https://github.com/ansiblebit/oracle-java/releases/tag/5.14.10

**Comment by steenzout** [comment]
@hryamzik I guess I don't need the warning on the README file now...
