### ISSUE TITLE
ansible-galaxy downloas old version (v4.14.2) of ansiblebit/oracle-java (instead of lastest 5.14.4)

### ISSUE THREAD

**Issue by roumano** [ansiblebit/oracle-java#39]
ansible-galaxy -vvv install ansiblebit.oracle-java
Using /etc/ansible/ansible.cfg as config file
Opened /home/fedora/.ansible_galaxy
Installing role ansiblebit.oracle-java 
Opened /home/fedora/.ansible_galaxy
- downloading role 'oracle-java', owned by ansiblebit
https://galaxy.ansible.com/api/v1/roles/?owner__username=ansiblebit&name=oracle-java
https://galaxy.ansible.com/api/v1/roles/3375/versions/?page_size=50
- downloading role from https://github.com/ansiblebit/oracle-java/archive/v4.14.2.tar.gz
- extracting ansiblebit.oracle-java to /home/fedora/svn/ansible/roles/ansiblebit.oracle-java
- ansiblebit.oracle-java was installed successfully
[DEPRECATION WARNING]: The comma separated role spec format, use the yaml/explicit format instead..
This feature will be 
removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
- dependency ansiblebit.launchpad-ppa-webupd8 is already installed, skipping.

cat ansiblebit.oracle-java/meta/.galaxy_install_info
{install_date: 'Fri Apr 14 12:42:57 2017', version: v4.14.2}

maybe it's due to the letter "v" on the version ?

**Comment by steenzout** [comment]
@roumano I think that's the problem.

I've tried to clear the old `v` versions but galaxy is stubborn: https://github.com/ansible/galaxy-issues/issues/251.

I suggest using a specific version to workaround your current problem plus it's safer in the long run (you don't want to end up breaking a playbook because you got a newer version of the role).

**Comment by steenzout** [comment]
@roumano just to be clear, you can install a specific version with a `requirements.yml` like:

```
- src: git@github.com:ansiblebit/oracle-java.git
  scm: git
  name: ansiblebit.oracle-java
  version: 5.14.4
```

or

```
- name: ansiblebit.oracle-java
  version: 5.14.4
```

and then executing:

```
$ ansible-galaxy install -r requirements.yml
```

I actually recommend using this way to install roles.

**Comment by steenzout** [comment]
ansible fixed the issue:

```
$ ansible-galaxy -vv install ansiblebit.oracle-java
No config file found; using defaults
- downloading role 'oracle-java', owned by ansiblebit
- downloading role from https://github.com/ansiblebit/oracle-java/archive/5.14.4.tar.gz
- extracting ansiblebit.oracle-java to /opt/local/etc/ansible/roles/ansiblebit.oracle-java
```

**Comment by steenzout** [comment]
please star the repo :)
