### ISSUE TITLE
Oracle java 7 for debian based system 

### ISSUE THREAD

**Issue by davejfranco** [ansiblebit/oracle-java#5]
when trying to install oracle version of java 7 I getting "msg: No package matching 'oracle-java7-installer' is available" and I think is because after you add the repo the roles is not making any update before trying yo install the package. I'm using Ubuntu server 14.04.

**Comment by steenzout** [comment]
interesting, I use Vagrant boxes to test the builds and I don't see that problem.
did you install the `ansiblebit.launchpad-ppa-webupd8` role as well?

I just checked and https://github.com/ansiblebit/launchpad-ppa-webupd8/blob/master/tasks/os_distribution/ubuntu.yml and it's true it doesn't update the cache either when I add the repo.

I can patch really quick but you'll need to update the  `ansiblebit.launchpad-ppa-webupd8` role.
is it worth giving a try?

**Comment by steenzout** [comment]
I've updated `launchpad-ppa-webupd8` let me know if this solves your problem.

**Comment by davejfranco** [comment]
It's just perfect, thank you.
