### ISSUE TITLE
Two small items 

### ISSUE THREAD

**Issue by aram535** [ansiblebit/oracle-java#51]
These are just warnings and they did not cause any major issues - figured I'd report them just in case

When running this against a CentOS 7 system, using: ansible 2.3.0.0:

> 
> TASK [ansiblebit.oracle-java : define download page URL based on latest version] ******************************************************************
>  [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: {{
> latest_java_page_and_version[1]|version_compare(oracle_java_version,'=') }}
> 
> ok: [server1]
> 
> TASK [ansiblebit.oracle-java : get lastest JDK rpm url] *******************************************************************************************
>  [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: {{
> latest_java_page_and_version[1]|version_compare(oracle_java_version,'!=') and oracle_java_version }}
> 
> skipping: [server1]
> 
> TASK [ansiblebit.oracle-java : define download page URL for "8"] **********************************************************************************
>  [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: {{
> latest_java_page_and_version[1]|version_compare(oracle_java_version,'!=') and oracle_java_version }}
> 
>

**Comment by steenzout** [comment]
I believe this has been fixed.
