### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by hryamzik** [ansiblebit/oracle-java#57]
```
 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: {{ latest_java_page_and_version[1]|version_compare(oracle_java_version,'=') }}
```

**Comment by redreboot** [comment]
![3853dce2-8593-4131-839b-c376d91f4372-1600-0000014898d96b81](https://user-images.githubusercontent.com/30930892/29746847-f2cd97c6-8aef-11e7-8378-471a77fa62e1.jpeg)
![img_0380](https://user-images.githubusercontent.com/30930892/29746848-f302a95c-8aef-11e7-9dd4-d42853c0af63.JPG)

**Comment by redreboot** [comment]
Image quality

**Comment by steenzout** [comment]
duplicate of https://github.com/ansiblebit/oracle-java/issues/51 ?

**Comment by hryamzik** [comment]
Right.
