### ISSUE TITLE
Setting java version doesn't work  on Redhat 

### ISSUE THREAD

**Issue by eugenemiretsky** [ansiblebit/oracle-java#65]
I tried setting both oracle_java_version_string and oracle_java_version_update and both seem to get ignored. 
It looks like the options are ignored, and the last version is installed. 

One of the debug messages is (I wanted to install u152, but u161 is being installed):  "msg": "Downloading java 8u152 to jdk-8u161-linux-x64.rpm from http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.rpm"
"

**Comment by dzatorsky** [comment]
Experiencing the same issue on Ubuntu 17.10. Tried to set versions as shown below:
```
oracle_java_version: 8
oracle_java_version_update: 152
oracle_java_version_build: 16
oracle_java_set_as_default: yes
```
As well as:
`oracle_java_version_string: 1.8.0_u152`
and
`oracle_java_version_string: 1.8.0_152`
Nothing helped. Version of ansiblebit.oracle-java is 5.14.14.

**Comment by steenzout** [comment]
@zatorsky you can't set individual versions on ubuntu.
the installation process uses a debian package so you'll always get the latest version that is on the `ppa:webupd8team/java`.
