### ISSUE TITLE
Link to Ansible Galaxy in description doesn't work

### ISSUE THREAD

**Issue by SwiftAdviser** [ansiblebit/oracle-java#66]
Your link: https://galaxy.ansible.com/detail#/role/3375 (empty page)
Working link: https://galaxy.ansible.com/ansiblebit/oracle-java/

Here:
![image](https://user-images.githubusercontent.com/5148967/36146784-710d140a-10be-11e8-93b2-76fa075a6873.png)

**Comment by steenzout** [comment]
fixed.
