### ISSUE TITLE
redhat: document oracle_java_download_timeout and increase default value

### ISSUE THREAD

**Issue by georgewilliamherbert** [ansiblebit/oracle-java#87]
I believe the timeouts are inadequate for Oracle's current responsiveness.  For a Redhat class system we experienced multiple failures today; I externally overrode the default 10 sec timeout in defaults/redhat.yml with 1000 sec and it completed in ~25 sec.  I recommend upping the defaults to at least 30 and preferrably 60; also, publicizing awareness of the oracle_java_download_timeout variable in case people see more failures.

**Comment by georgewilliamherbert** [comment]
https://github.com/ansiblebit/oracle-java/pull/88 . to set this to 60...

**Comment by steenzout** [comment]
fixed in the `develop` branch.
